#!/bin/bash
source .ssh.conf
ARGC="${#}"
ERR=$(getopt -o a:g:h:u: -l ip-address:,group:,host:,user: -- ${@} 2>&1 1>/dev/null)

main() {
    case "${1}" in
        # The parameterization needs to be modified.
        test)
            echo "test: ${OPT}"
        ;;
        
        add)
            source manual.sh
            cmd ${@} 
        ;;

        aws)
            source aws.sh
            aws_cmd ${@}
        ;;

        delete)
            echo "${@}"
        ;;

        list)
            echo "${@}"
        ;;

        update)
            echo "${@}"
        ;;

        help|*)
            echo -e "Usage: ${0} [OPTION] \n"
            echo "	add		Add host ssh config in folder."
            echo "	aws		AWS."
            echo "	delete		Delete host ssh config in folder."
            echo "	help		Print command options."
            echo "	list		List host of folder."
            echo "	update		Update host ssh config."
            echo "	test		Test function."
        ;;
    esac
}

main ${@}